# Generated by Django 4.2.5 on 2023-09-25 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydrasaveAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmaster',
            name='createdById',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrasaveAPI.usermaster'),
        ),
    ]
