# Generated by Django 4.2.5 on 2023-10-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrasaveAPI', '0002_alter_passmaster_passuniqueid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passmaster',
            name='passUniqueId',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='trainmaster',
            name='trainUniqueId',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
