# Generated by Django 4.2.5 on 2023-09-25 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydrasaveAPI', '0003_alter_usermaster_regionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='industryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='industryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hydrasaveAPI.industrymaster'),
        ),
    ]
