# Generated by Django 4.2.5 on 2023-09-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrasaveAPI', '0004_industrymaster_alter_usermaster_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='userId',
        ),
        migrations.AddField(
            model_name='otp',
            name='username',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
