# Generated by Django 4.2.5 on 2023-09-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydrasaveAPI', '0005_remove_otp_userid_otp_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
