# Generated by Django 4.2.5 on 2023-09-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydrasaveAPI', '0006_alter_usermaster_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='industryId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hydrasaveAPI.industrymaster'),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='regionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hydrasaveAPI.regionmaster'),
        ),
    ]
