# Generated by Django 4.2.5 on 2023-09-28 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hydrasaveAPI', '0007_alter_usermaster_industryid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantmaster',
            name='pincode',
        ),
    ]
