# Generated by Django 4.2.5 on 2023-09-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydrasaveAPI', '0008_remove_plantmaster_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementmaster',
            name='stageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='hydrasaveAPI.stagemaster'),
        ),
        migrations.AlterField(
            model_name='passmaster',
            name='trainId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='hydrasaveAPI.trainmaster'),
        ),
        migrations.AlterField(
            model_name='plantmaster',
            name='plantUniqueId',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='stagemaster',
            name='passId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='hydrasaveAPI.passmaster'),
        ),
        migrations.AlterField(
            model_name='stagemaster',
            name='stageUniqueId',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='trainmaster',
            name='plantId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trains', to='hydrasaveAPI.plantmaster'),
        ),
    ]
