# Generated by Django 4.2.5 on 2023-10-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hydrasaveAPI', '0009_alter_elementmaster_stageid_alter_passmaster_trainid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmaster',
            name='plantUniqueId',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='stagemaster',
            name='stageUniqueId',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='timeseriesdata',
            name='stageId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ts_data', to='hydrasaveAPI.stagemaster'),
        ),
    ]
